version: "3.9"

services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=zim_refuse_tracker.settings

  worker:
    build: .
    command: ["dramatiq", "refuse_tracker.tasks", "--processes", "1", "--threads", "2"]
    environment:
      - DJANGO_SETTINGS_MODULE=zim_refuse_tracker.settings
